### ISSUE TITLE
let's work together?

### ISSUE THREAD

**Issue by Slach** [blind-oracle/clickhouse-zabbix#1]
i'm also contributing to https://github.com/altinity/clickhouse-zabbix-template
lets look to work of each other 
and try to focus on work together?

**Comment by blind-oracle** [comment]
@Slach 

Привет! Без проблем.
Я видел, конечно, шаблоны от Altinity, но решил что хочу сделать без внешних скриптов если это возможно. Оно немножко коряво, благодаря ограничениям Заббикса, но работает.

Не коряво можно сделать, но тогда запросы будут идти от сервера, а не от агентов. В нашем случае это не подходит т.к. строгий файрволлинг везде...

**Comment by Slach** [comment]
ну ок, на самом деле было бы интересно делиться идеями по триггерам и графикам в мониторинге, моя телега @bloodjazman пиши если будут какие то мысли ;)
